version: '3.9'
services:

  aio:
    build: aio/
    container_name: aio
    environment:
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
      - PGDATA=/var/lib/postgresql/data/pgdata
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - ./data/stage:/home/data/stage
      - ./data/spark/notebooks:/home/iceberg/notebooks/notebooks
      - ./projects/dagster:/opt/dagster/app/
      - ./projects/dbt:/opt/dagster/dbt/
      - ./data/minio:/data
    ports:
      - '8888:8888' # Spark notebook port
      - '7077:7077' # Spark port
      - '8061:8061' # Spark master web ui port
      - '8062:8062' # Spark worker web ui port
      - '10000:10000' # Thrift ODBC/JDBC port
      - '18080:18080' # Spark history web ui port
      - '3070:3070' # dagit
      - '8060:8060' # trino
      - '33306:3306' # mysql
      - '9083:9083' # Metastore Thrift
      - '5432:5432' # Postgres
      - '9000:9000' # Minio
      - '9001:9001' # Minio
    networks:
      ndsnet:
        aliases:
          - mariadb
          - postgres
          - spark
          - dagster
          - dbt
          - trino
          - metastore
          - aio
          - minio
    command: 
      - notebook

  cube:
    image: cubejs/cube
    container_name: cube
    hostname: cube
    volumes:
      - ./conf/cube:/cube/conf
    ports:
      - 3000:3000 
      - 4000:4000
      - 3245:3245
    networks:
      - ndsnet
    depends_on:
      - aio

  metabase:
    container_name: metabase
    depends_on:
      - cube
    hostname: metabase
    build: metabase/
    volumes:
      - ./conf/metabase:/conf
    ports:
      - 3030:3030
    networks:
      - ndsnet
  
networks:
  ndsnet:
    driver: bridge
